# Generated by Django 3.2 on 2021-04-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('location', models.TextField()),
                ('contact_no', models.CharField(blank=True, max_length=10, null=True)),
                ('icu_beds_availablity', models.IntegerField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('DOB', models.DateTimeField()),
                ('symptoms', models.TextField()),
                ('oxygen_level', models.IntegerField()),
            ],
        ),
    ]
