# Generated by Django 3.2 on 2021-04-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
