# Generated by Django 3.2 on 2021-04-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_crm', '0002_alter_hospital_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiffin_service_provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=10)),
                ('timing', models.DateTimeField()),
                ('covid_food', models.BooleanField(default=False)),
            ],
        ),
    ]
