# Generated by Django 3.2 on 2021-04-27 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_crm', '0003_tiffin_service_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='location',
            field=models.TextField(choices=[('Vadodara', 'Vadodara'), ('Surat', 'Surat'), ('Ahmedabad', 'Ahmedabad'), ('Bharuch', 'Bharuch'), ('Rajkot', 'Rajkot'), ('Anand', 'Anand')]),
        ),
    ]
