# Generated by Django 3.2 on 2021-04-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_crm', '0004_alter_hospital_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='location',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='tiffin_service_provider',
            name='location',
            field=models.CharField(choices=[('Vadodara', 'Vadodara'), ('Surat', 'Surat'), ('Ahmedabad', 'Ahmedabad'), ('Bharuch', 'Bharuch'), ('Rajkot', 'Rajkot'), ('Anand', 'Anand')], default=None, max_length=500),
        ),
    ]
