# Generated by Django 3.2 on 2021-04-27 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid_crm', '0005_auto_20210427_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiffin_service_provider',
            old_name='title',
            new_name='name',
        ),
    ]
