# Generated by Django 3.2 on 2021-04-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_crm', '0006_rename_title_tiffin_service_provider_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiffin_service_provider',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
