# Generated by Django 3.2 on 2021-04-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_crm', '0008_tiffin_service_provider_tiffin_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiffin_service_provider',
            name='food_available',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
