# Generated by Django 3.2 on 2021-04-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_crm', '0009_tiffin_service_provider_food_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='user',
            name='oxygen_level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='food',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='oxygen',
            field=models.BooleanField(default=None),
        ),
    ]
