# Generated by Django 3.2 on 2021-04-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_crm', '0010_auto_20210429_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='acde@gmail.com', max_length=254, null=True),
        ),
    ]
