# Generated by Django 3.2 on 2021-04-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_crm', '0011_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('oxygen', models.BooleanField(default=None)),
                ('food', models.BooleanField(default=None)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
