# Generated by Django 3.2 on 2021-04-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_crm', '0012_auto_20210429_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_custom',
            name='mobile',
            field=models.IntegerField(max_length=10),
        ),
    ]
