# Generated by Django 3.2 on 2021-04-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_crm', '0013_alter_user_custom_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiffin_service_provider',
            name='tiffin_image',
            field=models.ImageField(default='static/images/cov_bg.png', upload_to='tf_image'),
        ),
    ]
