# Generated by Django 3.2 on 2021-04-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_crm', '0014_alter_tiffin_service_provider_tiffin_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiffin_service_provider',
            name='location',
            field=models.CharField(choices=[('Vadodara', 'Vadodara'), ('Surat', 'Surat'), ('Ahemdabad', 'Ahemdabad'), ('Bharuch', 'Bharuch'), ('Rajkot', 'Rajkot'), ('Anand', 'Anand')], default=None, max_length=500),
        ),
    ]
