# Generated by Django 3.2 on 2021-04-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_crm', '0015_alter_tiffin_service_provider_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_custom',
            name='free_service',
            field=models.BooleanField(default=None),
        ),
    ]
