# Generated by Django 3.2 on 2021-04-30 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_crm', '0017_alter_user_custom_free_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiffin_service_provider',
            name='free',
            field=models.BooleanField(default=False),
        ),
    ]
